included:
  - ../Gini
  - Example/

excluded:
  - Pods/

disabled_rules: # rule identifiers to exclude from running
  - trailing_newline
  - trailing_whitespace
  - large_tuple
  - identifier_name
  - colon

force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
line_length:
- 200 # warning
- 600 # error
function_body_length:
- 50 # warning
- 60 # error

identifier_name: warning
shorthand_operator: warning
