source 'https://github.com/gini/gini-podspecs.git'
source 'https://github.com/CocoaPods/Specs.git'
project 'Gini.xcodeproj'

platform :ios, '10.0'

target 'Example' do
  use_frameworks!
  pod 'Gini', :path => '../', :testspecs => ['Tests']
  pod 'Gini/DocumentsAPI', :path => '../'
  pod 'Gini/Pinning', :path => '../'
end
