project 'Gini.xcodeproj'

platform :ios, '10.0'

target 'Example' do
  use_frameworks!
  pod 'Gini', :path => '../', :testspecs => ['Tests']
  pod 'Gini/DocumentsAPI', :path => '../'
  pod 'Gini/Pinning', :path => '../'
end
